// <auto-generated />
using System;
using MailUptime.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailUptime.Migrations
{
    [DbContext(typeof(MailUptimeContext))]
    partial class MailUptimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MailUptime.Models.MailCheckRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FailPatternMatched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailedSubject")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMatchedSubject")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReceivedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailboxIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PatternMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MailboxIdentifier", "Day")
                        .IsUnique();

                    b.ToTable("MailCheckRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
